export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST"
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS"
export const CREATE_USER_FAIL = "CREATE_USER_FAIL"

export const CREATE_TOKEN_REQUEST = "CREATE_TOKEN_REQUEST"
export const CREATE_TOKEN_SUCCESS = "CREATE_TOKEN_SUCCESS"
export const CREATE_TOKEN_FAIL = "CREATE_TOKEN_FAIL"

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST"
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS"
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL"